//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcMVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayTinh
    {
        public string MaMay { get; set; }
        public string DongMay { get; set; }
        public Nullable<System.DateTime> NgaySX { get; set; }
        public string HangSX { get; set; }
        public string TenMay { get; set; }
        public Nullable<int> GiaBan { get; set; }
    }
}
